sudo: false
language: node_js
branches:
  except:
  - gh-pages
node_js:
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
before_script:
  - npm install grunt-cli -g
